### ISSUE TITLE
cant launch 1.8.9

### ISSUE THREAD

**Issue by Myth78** [ezfe/m1craft#28]
hello I'm revisiting this project after a while and I can't launch 1.8

**Comment by ezfe** [comment]
Let me take a look

**Comment by ezfe** [comment]
So...1.8.9 was never supported, but I broke the code that handles the errors. That being said, I'm going to look and see if I can tweak it to at least support running it. No idea if it'll start properly though.

**Comment by ezfe** [comment]
Unfortunately, the game does fail to start with older versions, including 1.8.9:

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/lwjgl/opengl/OpenGLException
	at net.minecraft.client.main.Main.main(SourceFile:41)
Caused by: java.lang.ClassNotFoundException: org.lwjgl.opengl.OpenGLException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	... 1 more
```

Versions prior to 1.19 require the LWJGL natives to be patched, and I don't have native ARM builds of these older LWGJL versions.

**Comment by ezfe** [comment]
I've removed versions prior to 1.14.2 from the version list to avoid confusion. This may take a few minutes to appear on your side.
